name: Build and deploy Python app to Azure Web App - SetMedicSA

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      # Step 1: Checkout the repository code
      - uses: actions/checkout@v4

      # Step 2: Set up the required Python version
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Set up virtual environment and install dependencies
      - name: Set up virtual environment and install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests to validate the application
      - name: Run tests
        run: |
          source venv/bin/activate
          pytest || echo "Tests failed!" # Notify if tests fail

      # Step 5: Package the application files into a zip artifact
      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . -x "venv/*" ".github/*" "*.git*" "tests/*"

      # Step 6: Upload the artifact for deployment
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # Step 1: Download the artifact from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      # Step 2: Unzip the artifact for deployment
      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Step 3: Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # Ensure AZURE_CREDENTIALS are stored securely in GitHub Secrets

      # Step 4: Deploy the application to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'SetMedicSA'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        continue-on-error: true # Allow workflow to proceed if deployment fails

      # Step 5: Handle deployment errors (Optional)
      - name: Notify deployment status
        if: failure()
              run: echo "Deployment failed! Please check the logs."